# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_tone_from_voice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('age', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
            ],
        ),
    ]
